# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径,输入http:localhost:8080/swagger-ui会自动重定向到swagger页面
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs  #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs: #分组配置,可配置多个分组
    - group: 'default'             #分组名称
      paths-to-match: '/**'        #配置需要匹配的路径
      packages-to-scan: com.cms    #配置要扫描包的路径,一般配置到启动类所在的包名
    - group: 'admin-api'
      paths-to-match: '/**'
      packages-to-scan: com.cms

## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true    #开启knife4j,无需添加@EnableKnife4j注解
#  setting:
#    language: zh_cn   #中文
#    swagger-model-name: 实体列表   #默认为：Swagger Models
#  #开启Swagger的Basic认证功能,默认是false,开启后访问文档页面时会弹出用户名和密码输入框
#  basic:
#    enable: true
#    # Basic认证用户名
#    username: user
#    # Basic认证密码
#    password: 123456